# -*- coding: utf-8 -*-
"""image angle test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12hpq0lP4_VItqryGfipek5Vhq7Zygy19
"""

from pathlib import Path
from PIL import Image
from IPython.display import display
import base64
import requests

# Define class
class OllamaImageDescriptor:
    def __init__(self, base_url: str = "http://localhost:11435"):
        self.base_url = base_url.rstrip('/')

    def encode_image(self, image_path: str) -> str:
        with open(image_path, "rb") as img_file:
            encoded_str = base64.b64encode(img_file.read()).decode("utf-8")
        return encoded_str

    def describe_image(self, image_path: str, model: str = "gemma3:4b") -> str:
        image_b64 = self.encode_image(image_path)
        payload = {
            "model": model,
            "prompt": "Describe this image in detail.",
            "images": [image_b64],
            "stream": False
        }
        response = requests.post(f"{self.base_url}/api/generate", json=payload)
        if response.status_code == 200:
            return response.json().get("response", "No description found.")
        else:
            return f"Error: {response.status_code} - {response.text}"

# Folder with your images
image_folder = Path(r"C:/Users/taran/OneDrive/Documents/thesis doc/IMAGE ANGLE TEST")
descriptor = OllamaImageDescriptor(base_url="http://localhost:11435")

# Retrieve all images in the folder
image_files = list(image_folder.glob("*.jpeg")) + list(image_folder.glob("*.jpg")) + list(image_folder.glob("*.png"))

# Angles to test
angles = [0, 45, 60, 90, 180, 270]

# Process each image in the folder
for image_path in image_files:
    print(f"Processing image: {image_path.name}")
    for angle in angles:
        try:
            img = Image.open(image_path)
            if angle != 0:
                img_rotated = img.rotate(-angle, expand=True)
                rotated_path = str(image_folder / f"rotated_{angle}_{image_path.name}")
                img_rotated.save(rotated_path)
                display(img_rotated)
                description = descriptor.describe_image(rotated_path, model="gemma3:4b")
                print(f"Description ({angle}° rotation):\n", description)
            else:
                display(img)
                description = descriptor.describe_image(str(image_path), model="gemma3:4b")
                print("Original Image Description:\n", description)
            print("-" * 80)
        except Exception as e:
            print(f"Could not process {image_path.name} at {angle}°: {e}")

