# -*- coding: utf-8 -*-
"""Image test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OdECQpemwluF3eMJrmOSe1j7cPERdsaP
"""

import base64
import requests

class OllamaImageDescriptor:
    def __init__(self, base_url: str = "http://localhost:11435"):
        self.base_url = base_url.rstrip('/')

    def encode_image(self, image_path: str) -> str:
        with open(image_path, "rb") as img_file:
            encoded_str = base64.b64encode(img_file.read()).decode("utf-8")
        return encoded_str

    def describe_image(self, image_path: str, model: str = "gemma3:4b") -> str:
        image_b64 = self.encode_image(image_path)
        payload = {
            "model": model,
            "prompt": "Describe this image in detail.",
            "images": [image_b64],
            "stream": False
        }
        response = requests.post(f"{self.base_url}/api/generate", json=payload)
        if response.status_code == 200:
            return response.json().get("response", "No description found.")
        else:
            return f"Error: {response.status_code} - {response.text}"

from pathlib import Path
from PIL import Image
from IPython.display import display

image_folder = Path(r"C:/Users/taran/OneDrive/Documents/thesis doc/Image Folder")
descriptor = OllamaImageDescriptor(base_url="http://localhost:11435")

# Collect jpg, jpeg, and png files
image_files = list(image_folder.glob("*.jpg")) + \
              list(image_folder.glob("*.jpeg")) + \
              list(image_folder.glob("*.png"))

for img_path in image_files:
    try:
        # Open and display original image
        img = Image.open(img_path)
        print(f"Original Image: {img_path.name}")
        display(img)
        description = descriptor.describe_image(str(img_path), model="gemma3:4b")
        print("Description of original:\n", description)

        # Rotate image 90 degrees clockwise
        img_rotated = img.rotate(-90, expand=True)
        print(f"\nRotated Image (90 degrees clockwise): {img_path.name}")
        display(img_rotated)

        # Save rotated image temporarily
        rotated_path = str(img_path.with_name("rotated_" + img_path.name))
        img_rotated.save(rotated_path)

        # Get description of rotated image
        description_rotated = descriptor.describe_image(rotated_path, model="gemma3:4b")
        print("Description of rotated:\n", description_rotated)
        print("-" * 80)

    except Exception as e:
        print(f"Failed for {img_path.name}: {e}")

