# -*- coding: utf-8 -*-
"""Random Imagetest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11PgD3bFYPB7OZus18K5bY6o0Rj_l8eeQ
"""

from pathlib import Path
from PIL import Image
from IPython.display import display
import base64
import requests
import pandas as pd

class OllamaImageDescriptor:
    def __init__(self, base_url: str = "http://localhost:11435"):
        self.base_url = base_url.rstrip('/')

    def encode_image(self, image_path: str) -> str:
        with open(image_path, "rb") as img_file:
            encoded_str = base64.b64encode(img_file.read()).decode("utf-8")
        return encoded_str

    def describe_image(self, image_path: str, model: str = "gemma3:4b", prompt: str = "Describe this image briefly.") -> str:
        image_b64 = self.encode_image(image_path)
        payload = {
            "model": model,
            "prompt": prompt,
            "images": [image_b64],
            "stream": False
        }
        response = requests.post(f"{self.base_url}/api/generate", json=payload)
        if response.status_code == 200:
            return response.json().get("response", "No description found.")
        else:
            return f"Error: {response.status_code} - {response.text}"

# Configure your image folder
image_folder = Path(r"C:/Users/taran/OneDrive/Documents/thesis doc/Random image test")
descriptor = OllamaImageDescriptor()

image_files = list(image_folder.glob("*.jpg")) + list(image_folder.glob("*.png")) + list(image_folder.glob("*.jpeg"))

results = []

for img_path in image_files:
    try:
        display(Image.open(img_path))

        # General brief description
        brief_desc = descriptor.describe_image(str(img_path), prompt="Describe this image briefly.")

        # Detailed description for profession, gender, age
        detailed_profession = descriptor.describe_image(
            str(img_path),
            prompt="Describe the profession of the people in the image, their approximate gender, and age."
        )

        print(f"Image: {img_path.name}")
        print("Brief Description:", brief_desc)
        print("Profession, Gender, Age Details:", detailed_profession)
        print("-" * 80)

        results.append({
            "Image Name": img_path.name,
            "Brief Description": brief_desc,
            "Profession Gender Age": detailed_profession
        })

    except Exception as e:
        print(f"Error processing {img_path.name}: {e}")

# Save results as CSV
df = pd.DataFrame(results)
df.to_csv(image_folder / "description_with_profession.csv", index=False)
print(f"Results saved to {image_folder / 'description_with_profession.csv'}")

